
spring:
  datasource:
      url: jdbc:mysql://101.132.146.171:3306/spring_shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8103

logging:
  level:
    com.crazyang.mapper: DEBUG
